chore(build-pipeline): :wrench: add job to check pipeline results

diff --git a/.github/workflows/build-pipeline.yml b/.github/workflows/build-pipeline.yml
--- a/.github/workflows/build-pipeline.yml
+++ b/.github/workflows/build-pipeline.yml
@@ -203,3 +203,19 @@ jobs:
 
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3
+
+  pipeline-complete:
+    if: always()
+    needs: [lint-and-test, build, trufflehog, codeql]
+    name: Build Pipeline Complete
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check job results
+        run: |
+          if [[ "${{ needs.lint-and-test.result }}" == "failure" || \
+                "${{ needs.build.result }}" == "failure" || \
+                "${{ needs.codeql.result }}" == "failure" ]]; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+          echo "All required jobs passed"
